development:
  adapter: sqlite3
  database: db/development_database.sqlite3
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: db/test_database.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/production_database
  pool: 5
  timeout: 5000