development:
  adapter: sqlite3
  database: development_database
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: test_database
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: production_database
  pool: 5
  timeout: 5000